### PR TITLE
Bullet rendering

### PR DESCRIPTION
**Pull request by ZackAmes**

### CODE REVIEW

**Comment by ZackAmes** [comment]
Moved bullets component from components into parent, Change bullet store type to more closly match model type and subscribed to changes in the models just like the player positions, including storing the start positions for replays.

**Review by 0xMugen — APPROVED** [review]
LGTM, good clean up. Like the bullet structure

**Review by 0xMugen — CHANGES_REQUESTED** [review]
This does break the bullet display though. and shoot is still called on record. 

Fix those b4 pushing

**Comment by ZackAmes** [comment]
refactors coord stores into own file, bullet sim working in client (simulating and updating from onchain state)

**Review by 0xMugen — APPROVED** [review]
LFG

**Pull request merged**
